- name: Deploy config
  become: true
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: restart_nginx
  with_items:
    - etc/nginx/nginx.conf
